# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'
        check-latest: false
    - name: Build with Maven
      env: # lookup key as an environment variable
        PWD: ${{ secrets.PWD }}
        URL: ${{ secrets.URL }}
        USER: ${{ secrets.USER }}
      run: mvn clean package