# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Deploy idFunction

on:
  push:
    branches: [ main ]
env: # lookup key as an environment variable
  AZURE_FUNCTIONAPP_NAME: idFunction
  POM_FUNCTIONAPP_NAME: idFunction
  POM_XML_DIRECTORY: '.'                     
  JAVA_VERSION: '11'                 

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: ${{ env.JAVA_VERSION }}
        check-latest: false     
    - name: 'Restore Project Dependencies Using Mvn'
      shell: bash
      run: |
        pushd './${{ env.POM_XML_DIRECTORY }}'
        mvn clean package
        mvn azure-functions:package
        popd
    - name: 'Run Azure Functions Deploy'
      uses: Azure/functions-action@v1.3.2
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: './${{ env.POM_XML_DIRECTORY }}/target/azure-functions/${{ env.POM_FUNCTIONAPP_NAME }}'
        publish-profile: ${{ secrets.AZURE_CREDS }}
        scm-do-build-during-deployment: true
        enable-oryx-build: true